# Generated by Django 4.2.6 on 2023-10-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='newswriter',
        ),
        migrations.DeleteModel(
            name='ArticleComment',
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
