# Generated by Django 4.2.6 on 2023-10-25 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcoment',
            old_name='article',
            new_name='product',
        ),
    ]
